### ISSUE TITLE
Docforth?

### ISSUE THREAD

**Issue by larsbrinkhoff** [programandala-net/glosara#1]
Would this be anything similar to Docforth?

http://www.excamera.com/sphinx/article-docforth.html

**Comment by programandala-net** [comment]
En/Je/On 2017-02-21 02:11, Lars Brinkhoff escribió / skribis / wrote :

> http://www.excamera.com/sphinx/article-docforth.html

Never heard of Docforth. I see its goal is different. Glosara extracts
the marked documentation from the Forth source files and builds an
Asciidoctor file out of it. I've just uploaded the repository, you can
take a look.

-- 
Marcos Cruz
http://programandala.net

**Comment by larsbrinkhoff** [comment]
Thank you!
